// actionTypes.js

export const FETCH_LIVE_SESSIONS_REQUEST = 'FETCH_LIVE_SESSIONS_REQUEST';
export const FETCH_LIVE_SESSIONS_SUCCESS = 'FETCH_LIVE_SESSIONS_SUCCESS';
export const FETCH_LIVE_SESSIONS_FAILURE = 'FETCH_LIVE_SESSIONS_FAILURE';

// Blog Categories
export const FETCH_BLOG_CATEGORIES_REQUEST = 'FETCH_BLOG_CATEGORIES_REQUEST';
export const FETCH_BLOG_CATEGORIES_SUCCESS = 'FETCH_BLOG_CATEGORIES_SUCCESS';
export const FETCH_BLOG_CATEGORIES_FAILURE = 'FETCH_BLOG_CATEGORIES_FAILURE';


// actionTypes.js

export const FETCH_BLOG_REQUEST = 'FETCH_BLOG_REQUEST';
export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS';
export const FETCH_BLOG_FAILURE = 'FETCH_BLOG_FAILURE';



export const FETCH_ALL_BLOG_REQUEST = 'FETCH_ALL_BLOG_REQUEST';
export const FETCH_ALL_BLOG_SUCCESS = 'FETCH_ALL_BLOG_SUCCESS';
export const FETCH_ALL_BLOG_FAILURE = 'FETCH_ALL_BLOG_FAILURE';


// constant/ActionTypes.js

export const FETCH_LUCKY_DRAWS_REQUEST = 'FETCH_LUCKY_DRAWS_REQUEST';
export const FETCH_LUCKY_DRAWS_SUCCESS = 'FETCH_LUCKY_DRAWS_SUCCESS';
export const FETCH_LUCKY_DRAWS_FAILURE = 'FETCH_LUCKY_DRAWS_FAILURE';


export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

